### PR TITLE
Added response logging including status code

### PR DESCRIPTION
**Pull request by seckek**
Implemented response logging which includes the status code and the raw response. This was done by processing the request when messageIsRequest is false in order to get the response / status info.

### CODE REVIEW

**Comment by righettod** [comment]
Hi, Thanks you very (x10000000) much for the PR 🥇 

I will take a look at it quickly (i'm little busy currently). 

I think I will add an option to enabled/disable the logging of the response, test it on real assessment to ensure that the extension did not break burp then release this as the **2.0.0** as it change the initial behavior of the extension 😃 

Thanks again 👍

**Comment by seckek** [comment]
Hey, thanks for having a look and for making the extension! Enabling/disabling the logging of the response sounds good - I wasn't sure how it would work with the extra columns so I left it without it for now but I think it is doable (maybe by altering the table to add 2 extra columns once logging of responses is included).

**Comment by righettod** [comment]
I will manage it 😃 
I will keep you informed. I must just find a slot to work on this point 😄

**Comment by righettod** [comment]
@seckek : I have merged the PR so, from now, all [night build](https://github.com/righettod/log-requests-to-sqlite/actions/workflows/gradle.yml) will contains your feature 👍 

I have also create this issue for me to track the release 2.0.0: #47

**Comment by righettod** [comment]
@seckek Hi, I finally manage to find time to start the release process, I'm working with PortSwigger to release the extension on the store...

**Pull request merged**
